# Generated by Django 3.1.7 on 2021-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_key',
            new_name='status_key',
        ),
    ]
