# Generated by Django 3.1.7 on 2021-03-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210311_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_key',
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='webapp.task', verbose_name='Task')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_task', to='webapp.type', verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type_key',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='webapp.TaskType', to='webapp.Type', verbose_name='Type'),
        ),
    ]
