# Generated by Django 3.1.7 on 2021-03-18 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210315_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Summary'),
        ),
    ]
