# Generated by Django 3.1.7 on 2021-04-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('user_delete_or_add_perm', 'Delete or add user permission')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
